import { Response } from 'express';
import { AuthRequest } from '../middleware/authMiddleware';
import Notes from '../models/Notes';
import { analyzeNoteContent } from '../services/aiService';

// @desc    Create new note with AI analysis and validation
// @route   POST /api/notes
// @access  Protected
export const createNote = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { title, content } = req.body;
    if (!title || !title.trim() || !content || !content.trim()) {
      res.status(400).json({ message: 'Title and content cannot be empty' });
      return;
    }

    // Call AI analyzer to validate and enrich the note
    const rawAnalysis = await analyzeNoteContent(title, content);
    let analysis: any;
    try {
      const cleaned = rawAnalysis.replace(/```json|```/gi, '').trim();
      analysis = JSON.parse(cleaned);
    } catch {
      // Fallback if JSON parsing fails
      analysis = {
        isTechRelated: true,
        summary: 'Summary generated by CareerGPT AI.',
        tags: ['Tech'],
        category: 'General Tech'
      };
    }

    if (!analysis.isTechRelated) {
      res.status(400).json({ message: 'This Learning Hub supports ONLY tech-related notes.' });
      return;
    }

    const note = await Notes.create({
      user: req.user!._id,
      title: title.trim(),
      content: content.trim(),
      summary: analysis.summary,
      aiSummary: analysis.summary,
      tags: analysis.tags || [],
      category: analysis.category || 'General Tech'
    });

    res.status(201).json({ success: true, note });
  } catch (error) {
    console.error('Create note failed:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// @desc    Get all notes (with search + category filter)
// @route   GET /api/notes
// @access  Protected
export const getNotes = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { search, category } = req.query;
    const query: any = { user: req.user!._id };
    if (search) {
      query.$text = { $search: search as string };
    }
    if (category) {
      query.category = category;
    }
    const notes = await Notes.find(query).sort({ updatedAt: -1 });
    res.json({ success: true, notes });
  } catch (error) {
    console.error('Get notes failed:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// @desc    Get single note
// @route   GET /api/notes/:id
// @access  Protected
export const getNoteById = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const note = await Notes.findOne({ _id: req.params.id, user: req.user!._id });
    if (!note) {
      res.status(404).json({ message: 'Note not found' });
      return;
    }
    res.json({ success: true, note });
  } catch (error) {
    console.error('Get single note failed:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// @desc    Update note with AI re-analysis on modification
// @route   PUT /api/notes/:id
// @access  Protected
export const updateNote = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { title, content, tags, category } = req.body;
    const noteId = req.params.id;

    const note = await Notes.findOne({ _id: noteId, user: req.user!._id });
    if (!note) {
      res.status(404).json({ message: 'Note not found' });
      return;
    }

    let updatedFields: any = { ...req.body };

    // If title or content changed, re-validate and update summary/tags/category automatically
    if ((title && title.trim() !== note.title) || (content && content.trim() !== note.content)) {
      const finalTitle = title ? title.trim() : note.title;
      const finalContent = content ? content.trim() : note.content;

      if (!finalTitle || !finalContent) {
        res.status(400).json({ message: 'Title and content cannot be empty' });
        return;
      }

      const rawAnalysis = await analyzeNoteContent(finalTitle, finalContent);
      let analysis: any;
      try {
        const cleaned = rawAnalysis.replace(/```json|```/gi, '').trim();
        analysis = JSON.parse(cleaned);
      } catch {
        analysis = {
          isTechRelated: true,
          summary: note.summary || note.aiSummary,
          tags: note.tags,
          category: note.category
        };
      }

      if (!analysis.isTechRelated) {
        res.status(400).json({ message: 'This Learning Hub supports ONLY tech-related notes.' });
        return;
      }

      updatedFields.summary = analysis.summary;
      updatedFields.aiSummary = analysis.summary;
      updatedFields.tags = analysis.tags || [];
      updatedFields.category = analysis.category || 'General Tech';
    }

    const updatedNote = await Notes.findOneAndUpdate(
      { _id: noteId, user: req.user!._id },
      { ...updatedFields },
      { new: true }
    );

    res.json({ success: true, note: updatedNote });
  } catch (error) {
    console.error('Update note failed:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// @desc    Analyze note content dynamically for frontend validation
// @route   POST /api/notes/analyze
// @access  Protected
export const analyzeNote = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { title, content } = req.body;
    if (!title || !title.trim() || !content || !content.trim()) {
      res.status(400).json({ message: 'Title and content are required' });
      return;
    }

    const rawAnalysis = await analyzeNoteContent(title, content);
    let analysis: any;
    try {
      const cleaned = rawAnalysis.replace(/```json|```/gi, '').trim();
      analysis = JSON.parse(cleaned);
    } catch {
      analysis = {
        isTechRelated: true,
        summary: rawAnalysis,
        tags: ['General'],
        category: 'General Tech'
      };
    }

    res.json({ success: true, analysis });
  } catch (error) {
    console.error('Note analysis failed:', error);
    res.status(500).json({ message: 'Failed to analyze note' });
  }
};

// @desc    Delete note
// @route   DELETE /api/notes/:id
// @access  Protected
export const deleteNote = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    await Notes.findOneAndDelete({ _id: req.params.id, user: req.user!._id });
    res.json({ success: true, message: 'Note deleted' });
  } catch (error) {
    console.error('Delete note failed:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// @desc    AI enhance note (Legacy endpoint, wraps enhanceNotes helper)
// @route   POST /api/notes/:id/enhance
// @access  Protected
export const enhanceNote = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const note = await Notes.findOne({ _id: req.params.id, user: req.user!._id });
    if (!note) {
      res.status(404).json({ message: 'Note not found' });
      return;
    }
    const rawAnalysis = await analyzeNoteContent(note.title, note.content);
    let analysis: any;
    try {
      const cleaned = rawAnalysis.replace(/```json|```/gi, '').trim();
      analysis = JSON.parse(cleaned);
    } catch {
      res.status(500).json({ message: 'Failed to enhance note' });
      return;
    }
    note.summary = analysis.summary;
    note.aiSummary = analysis.summary;
    note.tags = analysis.tags || [];
    note.category = analysis.category || 'General Tech';
    await note.save();
    res.json({ success: true, note });
  } catch (error) {
    console.error('Enhance note failed:', error);
    res.status(500).json({ message: 'Failed to enhance note' });
  }
};
